# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[>](bold black)"
error_symbol = "[x](bold red)"

[directory]
style = "bold black"

[git_branch]
style = "bold #C49BBB"

[git_status]
style = "bold yellow"

[nodejs]
style = "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
